# Generated by Django 5.1.4 on 2025-03-07 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('volume', models.IntegerField()),
                ('capitulo', models.IntegerField()),
                ('demografia', models.CharField(choices=[('SN', 'Shounen'), ('SJ', 'Shoujo'), ('SE', 'Seinen'), ('JO', 'Josei')], max_length=7)),
            ],
        ),
    ]
