# Generated by Django 5.1.4 on 2025-03-11 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangaapi', '0002_manga_cadastrado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mangaka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('sobrenome', models.CharField(max_length=255)),
            ],
        ),
    ]
